### ISSUE TITLE
Unsupported engine

### ISSUE THREAD

**Issue by 29-29** [MSU-Students/student-advising-portal#1]
The project doesn't support the latest Node engine.
```json
  "engines": {
    "node": "^20 || ^18 || ^16",
    "npm": ">= 6.13.4",
    "yarn": ">= 1.21.1"
  }
```

I have Node `v21.6.0` installed and I get this error when installing the modules with yarn:
```
error student-advising-portal@0.0.1: The engine "node" is incompatible with this module. Expected version "^20 || ^18 || ^16". Got "21.6.0"
```

**Comment by a1-hanif** [comment]
Is there any update on this issue?

**Comment by a1-hanif** [comment]
@29-29

**Comment by 29-29** [comment]
I believe this issue is on my end and my local machine. My machine has the latest LTS version of NodeJS (v22) while the project supports up to the previous LTS version (v20).

**Comment by Reyn4ldo** [comment]
Aight boys
