### ISSUE TITLE
SignUp / Login / Logout

### ISSUE THREAD

**Issue by fencim** [MSU-Students/student-advising-portal#12]
- Signin / Signup with Google Account
- Signup/Signin with email verification
- Logout
- SignIn as Student or Adviser (defer)
- Signin with Qr Code (defer)

**Comment by Epoyyy** [comment]
Noted sir!

**Comment by fencim** [comment]
Process for signIn with Email / Password
- SignUp with Email, Password, Fullname, Avatar (ConfirmPassword) , after submit(auto send email)
- [ ] Develop UI for Sigup Form with Email Password 
- [ ] Implement Logic Workflow and Store
- [ ] E2E QA

- Page for Email Verification( Your account is under email verification, check your email)
- [ ] Develop UI for Email Verification
- [ ] Implement Logic Workflow and Store
- [ ] E2E QA

- Forgot Password (Screen to enter email address)
- [ ] Develop UI for Frogot Password 
- [ ] Implement Logic Workflow and Store
- [ ] E2E QA

**Comment by fencim** [comment]
closing this issue
