### ISSUE TITLE
Problem in viewing my calendar

### ISSUE THREAD

**Issue by AmHussS** [MSU-Students/student-advising-portal#76]
Steps to replicate

1. Access the web-app link: https://gonana-o.web.app/
2. Log in as a student
3. then book an appointment in the calendar
![Screenshot 2024-12-19 172043](https://github.com/user-attachments/assets/adcbf580-1fba-401e-87dc-c30f197fb08f)
4. There is no sign of appointment in the calendar
![Screenshot 2024-12-19 172143](https://github.com/user-attachments/assets/165e3766-c71a-42f5-9892-aa8aff2bc6c8)

**Comment by fencim** [comment]
You issue is acceptable, defect, as it is not included in the Developemnt calendar view feature to booking of appointment, I will grab this task

**Comment by fencim** [comment]
please verify this , the fix is already been mereged

**Comment by AmHussS** [comment]
Good evening po sir I checked it and move the Task in the async collab

**Comment by AmHussS** [comment]
> please verify this , the fix is already been mereged

the problem is fixed po sir, for student to view a sign of appointment in the calendar

**Comment by AmHussS** [comment]
> please verify this , the fix is already been mereged

I'm sorry for not verifying it yesterday po sir, but I checked and moved the task in async collab regarding this issue po sir Thank you for informing po sir
